services:
  heisenberg-local-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src
    entrypoint: ["uvicorn"]
    command: ["app.main:socket_app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    container_name: "heisenberg"
