services:
  heisenberg-local-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: heisenberg:latest
    container_name: heisenberg-local-server
    ports:
      - "8000:8000"
      - "5678:5678"  # Remote debugger port
    volumes:
      - .:/usr/src
    # Let the CMD in Dockerfile handle the server startup
    # This will use uvicorn to keep the server running
    environment:
      - ENV=development
      - DEBUG_PORT=5678
      - DEBUG_MODE=${DEBUG_MODE:-false}  # Enable/disable remote debugging
      - HOT_RELOAD=${HOT_RELOAD:-false}   # Enable hot reload for development
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=heisenberg
      - POSTGRES_HOST=postgres
      - LOG_LEVEL=info  # General application log level
      - MONGO_LOG_LEVEL=error  # Set to ERROR to minimize MongoDB logs
      - UVICORN_LOG_LEVEL=info  # FastAPI/Uvicorn log level
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - OAUTH_REDIRECT_URL=http://localhost:8000/api/auth/callback
      - PYTHONDONTWRITEBYTECODE=1  # Don't write .pyc files
      - PYTHONUNBUFFERED=1  # Don't buffer stdout/stderr
    # depends_on:
    #   - postgres

  
#   postgres:
#     image: postgres:17.4
#     container_name: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: game_user_1
#       POSTGRES_PASSWORD: game_master_1
#       POSTGRES_DB: heisenberg
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
